### ISSUE TITLE
Create a requirements.txt file.

### ISSUE THREAD

**Issue by TallGorilla** [Harsha200105/DesktopAssitant#18]
`pip3 freeze > requirements.txt`

**Comment by Harsha200105** [comment]
@TallGorilla : someone's actually working on that

**Comment by TallGorilla** [comment]
nice

**Comment by TallGorilla** [comment]
> @TallGorilla : someone's actually working on that

nice

**Comment by Harsha200105** [comment]
@TallGorilla : No problem just choose a specific issue and start working just incase if you want to
